-- ============================================================
-- ⚠️  DEPRECATED — Gunakan shopee-sync-schema.sql yang lebih lengkap
--    File ini TIDAK PERLU dijalankan. Hanya disimpan sebagai referensi.
--    shopee-sync-schema.sql sudah mencakup:
--      - product_id BIGINT (bukan INT)
--      - kolom shopee_account
--      - index tambahan
--      - RLS + policies
-- ============================================================
-- JANGAN jalankan file ini jika shopee-sync-schema.sql sudah dijalankan.
-- ============================================================
